#! /bin/bash

echo "Running git pre-commit hook"

./gradlew ktlintCheck
./gradlew ktlintFormat
./gradlew ktlintCheck
--warning-mode=(all,fail,none,summary)

RESULT=$?

# return 1 exit code if running checks fails
[ $RESULT -ne 0 ] && exit 1
exit 0